### ISSUE TITLE
Issue while opening

### ISSUE THREAD

**Issue by pranav2w** [GameInstitutes/HTML5Demo#1]
First of all thanks for project.

Whenever I had tried to open **HTML5Demos.uproject** file, it is showing me below message.
![message 1](https://user-images.githubusercontent.com/12233807/28202506-56aa3e04-6893-11e7-8dbd-f00226bdd7db.JPG)

After click on YES it is showing me below error.
![error](https://user-images.githubusercontent.com/12233807/28202544-79d86a68-6893-11e7-9bd0-511ac0b5d07b.JPG)

Here is attached **log file**

[HTML5Demos.docx](https://github.com/GameInstitutes/HTML5Demo/files/1147654/HTML5Demos.docx)

Am I doing anything wrong?

**Comment by GameInstitutes** [comment]
You needed to compile the plugin, but in this repos I had not include the cef.
You can update your local repos to download the missing files.
